name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            nix-system: x86_64-linux
          - runs-on: ubuntu-24.04-arm
            nix-system: aarch64-linux

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Flake check
        run: nix flake check

      - name: Build zeta
        run: nix build .#packages.${{ matrix.nix-system }}.zeta -L
