name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build Linux x86_64 binary
        run: nix build .#packages.x86_64-linux.zeta

      - name: Build Linux aarch64 binary
        run: nix build .#packages.aarch64-linux.zeta

      - name: Build macOS x86_64 binary
        run: nix build .#packages.x86_64-darwin.zeta

      - name: Build macOS aarch64 binary
        run: nix build .#packages.aarch64-darwin.zeta

      - name: Prepare binaries
        run: |
          mkdir dist
          cp result/bin/zeta dist/zeta-linux-amd64
          cp result-2/bin/zeta dist/zeta-linux-arm64
          cp result-3/bin/zeta dist/zeta-macos-amd64
          cp result-4/bin/zeta dist/zeta-macos-arm64
          chmod +x dist/* || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/zeta-linux-amd64
            dist/zeta-linux-arm64
            dist/zeta-macos-amd64
            dist/zeta-macos-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
